FROM python:3.10-slim

# Set working directory
WORKDIR /app

COPY AIML/requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt
COPY AIML/ ./


# Expose port
EXPOSE 5001

# Command to run FastAPI server
CMD ["uvicorn", "api:app", "--host", "0.0.0.0", "--port", "5001"]
