FROM python:3.10-slim

# Set working directory
WORKDIR /app

COPY Devops_Integration/ai_requirements.txt ./requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
COPY Devops_Integration/ai_service.py ./ai_service.py

# Expose port
EXPOSE 5001

# Command to run FastAPI server
CMD ["uvicorn", "ai_service:app", "--host", "0.0.0.0", "--port", "5001"]
